// Rehydration store
export const REHYDRATION_SET_REHYDRATION_VALUE =
    'REHYDRATION_SET_REHYDRATION_VALUE';

// COMMON ACTIONS
export const COMMON_RESET_LOCAL_STATE = 'COMMON_RESET_LOCAL_STATEs';

// CONTAINER ACTIONS
export const CONTAINER_SET_CONTROLS = 'CONTAINER_SET_CONTROLS';
export const CONTAINER_SET_CURRENT_SCREEN_NAME =
    'CONTAINER_SET_CURRENT_SCREEN_NAME';

export const CONTAINER_SET_WELCOME_SCREEN = 'CONTAINER_SET_WELCOME_SCREEN';

// AUTH ACTIONS
export const USER_SET_LOGIN = 'USER_SET_LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_SET_SIGNUP_DETAILS = 'AUTH_SET_SIGNUP_DETAILS';
export const AUTH_SET_SIGNIN_DETAILS = 'AUTH_SET_SIGNIN_DETAILS';
